version: "3.8"
services:
  loki:
    image: grafana/loki:2.9.0
    ports: ["3100:3100"]
  promtail:
    image: grafana/promtail:2.9.0
  grafana:
    image: grafana/grafana:10.4.2
    ports: ["3000:3000"]
  prometheus:
    image: prom/prometheus:v2.54.1
    ports: ["9090:9090"]
