name: Code Scan (SAST + SCA + Secrets)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit pip-audit

      - name: Bandit - Static Analysis
        run: |
          bandit -r app/ -f txt -o bandit-report.txt || true

      - name: pip-audit - Dependency Scan
        run: |
          pip-audit -r requirements.txt -f json -o pip-audit.json || true

      - name: Gitleaks - Secrets Detection
        uses: gitleaks/gitleaks-action@v2
        with:
          config-path: .gitleaks.toml
          report-format: sarif
          report-path: results.sarif
