name: Code Security (SAST + SCA + Secrets)

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bandit semgrep pip-audit

      # --- SAST: Bandit ---
      # CI-PERMISSIVE: keep || true while tuning; remove it to block merges.
      - name: Run Bandit (SAST)
        run: |
          bandit -r app/ -f json -o bandit-report.json || true

      # --- SAST: Semgrep ---
      # --error makes Semgrep exit non-zero on findings when we later set severities.
      - name: Run Semgrep (SAST)
        run: |
          semgrep scan --config auto app/ --json > semgrep-report.json || true

       # --- SCA: Dependencies ---
      - name: Run pip-audit (SCA)
        run: |
          pip-audit -r requirements.txt -f json -o pip-audit-report.json || true

      # --- Secrets: Gitleaks ---
      - name: Run Gitleaks (Secrets)
        uses: gitleaks/gitleaks-action@v2
        with:
          report-format: sarif
          report-path: results.sarif

      # --- Publish reports for PR review ---
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: security-reports
          path: |
            bandit-report.json
            semgrep-report.json
            pip-audit-report.json
          if-no-files-found: ignore
