name: Observability & Slack Notifications

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: "0 9 * * 1"  # Mondays 09:00 UTC

permissions:
  contents: read

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install requests
        run: pip install requests

      - name: Send Slack notification
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python3 scripts/notify_slack.py
