name: Security Reporting (v2)
on:
  workflow_dispatch:
  schedule:
    - cron: "0 7 * * *"

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Generate consolidated report
        run: |
          echo "[INFO] Starting report generation..."
          python3 scripts/generate-report.py
          echo "[INFO] Files in workspace:"
          ls -la

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: security-summary
          path: ./security-report.md
