name: Threat Model Validation CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  threat-model-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Dependencies
        run: pip install pyyaml

      - name: Validate Threat Model
        run: python threat_model/validate_threats.py
